spring.application.name=courtSync
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/courtsync
spring.datasource.username=courtsync_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


whatsappmeow.base-url=${WHATSAPPMEOW_BASE_URL:http://localhost:9090}